# Generated by Django 2.2.1 on 2019-06-03 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id_dependencia', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre_dependencia', models.CharField(max_length=50)),
                ('abreviatura_dependencia', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id_facultad', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre_facultad', models.CharField(max_length=100)),
                ('abreviatura_facultad', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Resolucion',
            fields=[
                ('nro_resolucion', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('fecha_resolucion', models.DateField()),
                ('link_descarga', models.CharField(max_length=100)),
                ('anio_resolucion', models.CharField(max_length=4)),
                ('estado_resolucion', models.CharField(max_length=20)),
                ('observacion', models.TextField()),
                ('adjunto', models.CharField(max_length=100)),
                ('tipo_elevacion', models.CharField(max_length=50)),
                ('facultad_resolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resoluciones.Facultad')),
            ],
            options={
                'ordering': ('-fecha_resolucion',),
            },
        ),
        migrations.CreateModel(
            name='Resolutivo',
            fields=[
                ('id_resolutivo', models.AutoField(primary_key=True, serialize=False)),
                ('nro_resolutivo', models.IntegerField()),
                ('descripcion_resolutivo', models.TextField()),
                ('resolucion_resolutivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resoluciones.Resolucion')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('dni', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre_persona', models.CharField(max_length=100)),
                ('apellidos_persona', models.CharField(max_length=100)),
                ('tipo_persona', models.CharField(max_length=50)),
                ('resoluciones', models.ManyToManyField(to='resoluciones.Resolucion')),
            ],
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('nro_expediente', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('descripcion_expediente', models.TextField()),
                ('fecha_expediente', models.DateField()),
                ('dependencia_expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resoluciones.Dependencia')),
                ('facultad_expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resoluciones.Facultad')),
                ('resolucion_expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resoluciones.Resolucion')),
            ],
        ),
        migrations.AddField(
            model_name='dependencia',
            name='facultad_dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resoluciones.Facultad'),
        ),
        migrations.CreateModel(
            name='Considerando',
            fields=[
                ('id_considerando', models.AutoField(primary_key=True, serialize=False)),
                ('nro_considerando', models.IntegerField()),
                ('descripcion_considerando', models.TextField()),
                ('resolucion_considerando', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resoluciones.Resolucion')),
            ],
        ),
    ]
